version: "3"

services:
  laravel:
    build:
      context: ./docker/
      dockerfile: laravel.Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/share/nginx/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  http-nginx:
    image: nginx:1.14.2-alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./docker/http-nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - .:/usr/share/nginx/html:cached
    links:
      - laravel
      - mysql
      - redis
  mysql:
    image: mysql:${MYSQL_VERSION}
    # container_name: dbsc
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${APP_TIME_ZONE}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:alpine
    ports:
      - "6778:6379"
